### ISSUE TITLE
Using quotes in symbol syntactic sugar for hashes will break syntax highlight

### ISSUE THREAD

**Issue by ynilu** [zenspider/enhanced-ruby-mode#103] opened 2017-02-06 04:18 UTC
![2017-02-06 12 07 58](https://cloud.githubusercontent.com/assets/14059513/22634484/325867ec-ec65-11e6-8797-1aaacd1c63ea.png)

**Comment by yxhuvud** [comment] 2017-03-14 09:10
Duplicate of #97, no? (I'm glad to see a fix!)

**Closed** 2017-04-18 04:46 UTC
