### ISSUE TITLE
Streaming API indent not correctly.

### ISSUE THREAD

**Issue by zw963** [zenspider/enhanced-ruby-mode#85] opened 2015-07-24 09:33 UTC
```ruby
   # enh-ruby-mode
    order_params = ActionController::Parameters.new(params)
    .permit(...)
```

```ruby
   # ruby-mode, correct
    order_params = ActionController::Parameters.new(params)
      .permit(...)
```

**Comment by zenspider** [comment] 2015-07-25 21:55
This looks like a dupe of #83.

**Closed by zenspider** 2015-07-25 21:55 UTC

**Comment by zw963** [comment] 2017-01-03 10:40
I switch back to enh-ruby-mode ... : )

@zenspider , this still not work for me for now. (2017)

When exist follow content
```rb
foo
.bar
```
if I run `(indent-region (point-min) (point-max))`

No anythings happen for this file.

still 
```ruby
foo
.bar
```

**Comment by zenspider** [comment] 2017-01-03 23:14
Welcome back. Can you pile on in #83 ? This ticket is a dupe (I think)

**Comment by zw963** [comment] 2017-01-04 07:30
OK, I will describe in that issue. 

Thanks.

**Comment by zw963** [comment] 2017-02-03 08:12
Hi, @zenspider , I found the real reason cause those indent failed ...

The ruby version ...

I use ruby 2.2.2 parser, it is not indent correct, but when I switch to 2.1.6, it worked!

Do you have plan to fix this? 

Following link is the download url for traveling-ruby which create by [this project](https://github.com/phusion/traveling-ruby)

You can just download it to reproduce. Thanks.
http://d6r77u77i8pq3.cloudfront.net/releases/traveling-ruby-20150715-2.2.2-linux-x86_64.tar.gz

**Comment by zw963** [comment] 2017-02-03 08:15
Please like my know if you don't have any plan to support ruby 2.2.2.

Thanks very much.

It that, I will spend time to switch to old traveling ruby version just for worked well
with enh-ruby-mode.
