### ISSUE TITLE
Frozen String Literal Magic Comment Causes "error in process filter: erm-parse: Beginning of buffer" 

### ISSUE THREAD

**Issue by sgnr** [zenspider/enhanced-ruby-mode#94] opened 2016-02-16 21:09 UTC
Hi,

I hit an issue where I get a "error in process filter: erm-parse: Beginning of buffer" anytime I type in a buffer where there is the magic comment `# frozen_string_literal: true`.

Steps to reproduce:
* `emacs -q`.
* Load `enh-ruby-mode`.
* Type `# frozen_string_literal: true`.
* Type anything else in the buffer.

```
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ emacs --version
GNU Emacs 24.5.1
```
I'm using the ELPA version of `enh-ruby-mode` from Nov. 23rd, 2015.

Thanks

**Comment by bilus** [comment] 2016-03-13 23:18
Same here. It's a big issue because it makes editing very painful and slow.

**Comment by zenspider** [comment] 2016-03-16 03:07
Trying to repro and currently failing. I'll upgrade from 2.3.0 preview to final and see if that is it.

**Comment by senny** [comment] 2016-04-27 06:49
@zenspider any idea how I could work around this issue? I'm on a project where the `# frozen_string_literal: true` comment is in most files. I'm forced to fall back to `ruby-mode` as editing is nearly impossible otherwise. Thanks for your efforts.

**Comment by zenspider** [comment] 2016-04-27 20:43
@senny I can't offer a workaround until someone offers me reproduction steps. Sorry.

**Comment by senny** [comment] 2016-04-29 10:24
@zenspider how can I help you to get that reproduction?

Currently I'm seeing the error constantly when editing files with the `# frozen_string_literal: true` comment.

My Environment:
- `rbenv`
- `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
- `enh-ruby-mode-20151123.141`

**Comment by zenspider** [comment] 2016-05-17 00:54
My steps:

1. Created a file with your file content.
2. `C-x customize-variable RET enh-ruby-program RET` and set to `"/Users/ryan/.rbenv/versions/2.3.1/bin/ruby"`
3. Went back to original buffer
4. `C-x erm-reset`
5. typed extra code into buffer

No errors anywhere.

**Comment by marktran** [comment] 2016-05-17 06:14
I just discovered this error today too.

Any file with `# frozen_string_literal: true` causes the error. Using `2.3.1`.

**Comment by zenspider** [comment] 2016-05-17 10:32
That's clearly not the case, as I've shown,.. If you can actually help me reproduce this, great... But a "me too" does nothing to help.

**Comment by marktran** [comment] 2016-05-17 11:55
Here are the precise steps to reproduce:

1. `rbenv global 2.3.1`
2. `emacs -q`
3. M-x `load-file`
4. `/Users/mark/src/mark/emacs.d/elpa/enh-ruby-mode-20151123.141/enh-ruby-mode.el`
5. M-x `find-file`
6. `~/foo.rb`
7. M-x `enh-ruby-mode`
8. Type out `# frozen_string_literal: true`
9. [Return], [Return], [Return]
10. You'll see `error in process filter: Beginning of buffer` in your minbuffer.

Also, here is the error in `*Messages*`:
```
error in process filter: while: Beginning of buffer
error in process filter: Beginning of buffer
error in process filter: while: Beginning of buffer
error in process filter: Beginning of buffer
error in process filter: while: Beginning of buffer
error in process filter: Beginning of buffer
```

**Comment by marktran** [comment] 2016-05-17 11:57
Input just freezes after I enter `# frozen_string_literal: true` if my global Ruby version is not 2.3.1 and I later `customize-variable enh-ruby-program` to 2.3.1.

**Comment by zenspider** [comment] 2016-05-17 22:06
@marktran your repro steps don't work for me.

If you run with `emacs -q`, `enh-ruby-mode.el` defaults to `"ruby"` for its parser, can you ensure that that is what is being seen by your emacs? Something like `M-! ruby -v` should(?) suffice.

**Comment by marktran** [comment] 2016-05-18 03:31
Yup, mine defaults to `"ruby"` and uses 2.3.1 set through `rbenv global 2.3.1`. `/Users/mark/.rbenv/shims` is at the head of my `$PATH`.

This is the output of `M-! ruby -v`: `ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`

**Comment by zenspider** [comment] 2016-05-18 06:35
Are you running gui emacs or terminal. gui emacs on osx doesn't inherit your $PATH. That's what I'm worried about. Otherwise, I'm at a loss because it works fine for me even with your steps.

**Comment by zenspider** [comment] 2016-05-18 06:35
Anything else about your environment might be different? Encodings? I dunno. I'm at a loss.

**Comment by senny** [comment] 2016-05-18 07:00
@zenspider I can only vaguely remember but I think I did not get these errors from the get go. I must have changed something else on my config that's triggering the issue. We since moved away from having the comment in every file but if I try to experiment a bit and see if I can find a trigger.

**Comment by marktran** [comment] 2016-05-18 10:16
@zenspider I'm running terminal emacs, installed through Homebrew with `brew install emacs`. I can't think of anything else that would be different.

@senny Can you confirm if you can reproduce with the steps I posted above? I think this should be reproducible with a vanilla `emacs -q`...

**Comment by marktran** [comment] 2016-05-18 11:16
@zenspider What do your `$PATH`, `ruby -v`, and `which ruby` look like? Can't think of any other reason you wouldn't be able to repro other than Ruby version.

**Comment by zenspider** [comment] 2016-05-18 20:01
I think I'm going to extend the server process to log all communication so we can see what is being given said and how they might differ between us.

**Comment by packrat386** [comment] 2016-05-25 14:32
For what it's worth, if I switch to ruby 2.2 it works fine. In case anyone was looking for a quick fix.

**Comment by sockmonk** [comment] 2016-07-21 20:27
@zenspider I started seeing this problem when I upgraded to ruby-2.3.1 and the latest rubocop, which had me add the `# frozen_string_literal: true` to all my files. Using gui Emacs on OSX, M-! ruby -v confirms it's seeing ruby-2.0.0.  I'm using the chruby package like so:
(require 'chruby)
(chruby "ruby-2.3.1")

For now, I'm going to work around this by taking out that header line and disabling the rubocop check for it. Let me know if I can help with a fix.

**Comment by msuess** [comment] 2016-08-10 13:15
I also have this problem. Running on OSX, spacemacs (evil), Emacs 24.5. However, behaviour does not change based on what `M-! ruby -v` sees. It DOES change however if I set my local ruby version to 2.2.1.

**Comment by hosh** [comment] 2016-08-16 23:45
I also have this problem. I am using the emacs-nox package from Ubuntu 16 (24.5.1) running terminal emacs. I did not have this issue until I started using 2.3.1.

I also suspect this has something to do with Ruby 2.3 vs 2.2. Ruby 2.2 should be ignoring that magic comment. I wonder if Ruby 2.3 treats that magic comment differently in a way that breaks things.

**Comment by hosh** [comment] 2016-08-16 23:58
@zenspider do you want to try a video chat / hangout / etc. sometime to reproduce this? If you are interested, ping me at talktohosh at gmail.com and let's set up a time convenient for both of us. 

Alternatively: I can prep a VirtualBox image that reproduces this and ship it over to you.

Using Ruby 2.2 is good enough for now, but I do want to be able to use EnhRuby going forward with 2.3.

**Comment by hosh** [comment] 2016-08-17 00:26
I tried testing this with the test suite on the master branch of this repo (emacs-nox, 24.5.1, Ruby 2.3.1). The test command I used is:

```
emacs -batch -l ert -l enh-ruby-mode-test.el -f ert-run-tests-batch-and-exi
```

Without modifications:

```
Ran 12 tests, 11 results as expected, 1 unexpected (2016-08-17 00:18:20+0000)
2 expected failures

1 unexpected results:
   FAILED  enh-ruby-indent-leading-dots
```

When I added 
```
# frozen_string_literal: true
```

at the top of the `rubytest.rb` file, I get these results:

```
Ran 12 tests, 8 results as expected, 4 unexpected (2016-08-17 00:20:32+0000)
2 expected failures

4 unexpected results:
   FAILED  enh-ruby-backward-sexp-test
   FAILED  enh-ruby-forward-sexp-test
   FAILED  enh-ruby-indent-leading-dots
   FAILED  enh-ruby-up-sexp-test
```

Just to be complete, I tried a different comment at the top of the file, 

```
# Random Comment
```

```
Ran 12 tests, 11 results as expected, 1 unexpected (2016-08-17 00:21:18+0000)
2 expected failures

1 unexpected results:
   FAILED  enh-ruby-indent-leading-dots
```

And when I switch to Ruby 2.2.5 using rbenv with the magic comment, oddly, I get:

```
Ran 12 tests, 8 results as expected, 4 unexpected (2016-08-17 00:22:33+0000)
2 expected failures

4 unexpected results:
   FAILED  enh-ruby-backward-sexp-test
   FAILED  enh-ruby-forward-sexp-test
   FAILED  enh-ruby-indent-leading-dots
   FAILED  enh-ruby-up-sexp-test
```

That is weird because the Ruby 2.2.5 workaround works for me, so I am not sure what is going on with this.

**Comment by hosh** [comment] 2016-08-17 00:47
Ok, so part of the problem is this: https://github.com/zenspider/enhanced-ruby-mode/blob/master/ruby/erm_buffer.rb#L640-L641

If there is anything that goes wrong on the ruby side, then the error is silently dropped. I did also see some instances where immutable strings might be modified, such as https://github.com/zenspider/enhanced-ruby-mode/blob/master/ruby/erm_buffer.rb#L167 ... but I'm going to try getting rid of the rescue and see what surfaces up.

**Comment by zenspider** [comment] 2016-08-18 00:21
I believe that I finally isolated this and fixed it in c4e8803

Please test against master and let me know if you have further issues.

**Comment by zenspider** [comment] 2016-08-18 00:27
@hosh I'm not sure I agree with your analysis... but I'd love to see what bubbles up from removing that rescue. 

_Afterwards_, please test current master and let me know if the issue is resolved for you.

**Comment by CyborgMaster** [comment] 2016-08-18 16:49
The only productive thing I might be able to add to this discussion is that it seems that swapping my ruby version from 2.3.1 to 2.3.0 seems to fix things for me.

**Comment by zenspider** [comment] 2016-08-18 18:00
Huh... I was testing with 2.3.1. Can you try to get me a repro with your issue?

**Comment by CyborgMaster** [comment] 2016-08-18 18:04
@zenspider, if you are referring to you master fix from c4e8803, I wasn't testing that.  I've installed enh-ruby-mode using the emacs package manager (`package-list-packages`) and I'm not sure how to get it to install off of master, so I'm just using the latest version on melpa, which is 20160817.1711.  On that version, 2.3.1 gives me the error, but 2.3.0 does not.  

Sorry if I caused additional confusion.

**Comment by zenspider** [comment] 2016-08-18 18:11
Yes, I'd like a repro with 2.3.1 if you can provide one.

**Comment by zenspider** [comment] 2016-08-18 19:39
@CyborgMaster to help:

`M-x customize-variable RET debug-ignored-errors RET`

Then remove `beginning-of-buffer` and click `State` and then `Save for Current Session`

Then `M-x toggle-debug-on-error RET`

Now a repro will get you a backtrace that you can either poke at or paste here.

**Comment by zenspider** [comment] 2016-08-20 20:34
Anyone?

**Comment by marktran** [comment] 2016-08-21 10:19
@zenspider Yep, it's fixed on `master` for me.

**Comment by zenspider** [comment] 2016-08-21 18:37
Good enough for me. Closing. Please file a new issue if you encounter something like this.

**Closed by zenspider** 2016-08-21 18:37 UTC

**Comment by hosh** [comment] 2016-08-23 23:26
Same here.

**Comment by zenspider** [comment] 2016-08-23 23:51
Fantastic. Thank you.
