### ISSUE TITLE
Syntax Highlighting and Indenting Not Working

### ISSUE THREAD

**Issue by terryfinn** [zenspider/enhanced-ruby-mode#76] opened 2015-04-07 03:31 UTC
I can not get syntax highlighting to work in enh-ruby-mode. It works fine in ruby-mode, but when enh-ruby-mode is truned on everything is just black text, and auto indent stops working. I am running emacs 24.4.1 on Debian Wheezy, and I installed version 20150312.1458 of enh-ruby-package from melpa archive.

![screenshot from 2015-04-06 23 22 07](https://cloud.githubusercontent.com/assets/584017/7016543/6732bfd4-dcb4-11e4-99d1-7b76b2a46339.png)

**~/.emacs.d/init.el**
```elisp
(load "package")
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

;; Installs version 20150312.1458 of enh-ruby-package from melpa
(package-refresh-contents)
(package-install 'enh-ruby-mode)

(add-to-list 'load-path "(path-to)/Enhanced-Ruby-Mode") ; must be added after any path containing old ruby-mode
(autoload 'enh-ruby-mode "enh-ruby-mode" "Major mode for ruby files" t)
(add-to-list 'auto-mode-alist '("\\.rb$" . enh-ruby-mode))
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))
```

**Comment by zenspider** [comment] 2015-04-07 09:23
This doesn't reproduce on my end. Running in GUI on OSX with -q, loading your elisp above, and then opening a file with the same content produces this for me:

![screen shot 2015-04-07 at 02 22 51](https://cloud.githubusercontent.com/assets/9832/7020342/1af23b68-dccd-11e4-92af-83e62bd28aac.png)

**Comment by zenspider** [comment] 2015-04-07 09:25
I should have added, The emacs I'm running is 24.4.1 as well.

Can you run with -q and run your code fresh?

**Comment by terryfinn** [comment] 2015-04-07 11:31
Same effect:
![screenshot from 2015-04-07 07 30 22](https://cloud.githubusercontent.com/assets/584017/7022269/fbc70d1a-dcf7-11e4-8675-e31184980828.png)

**Comment by zenspider** [comment] 2015-04-07 23:00
and that was with `emacs -q` ??? odd.

I'm gonna have to assume something is wonky with your emacs package. Can you re-try with `-Q`, it's a bit more restrictive. I do this:

```
% /MyApplications/Emacs.app/Contents/MacOS/Emacs -Q -l bug01.el blah.rb 
```

and come out with properly syntax highlighted code.

**Comment by terryfinn** [comment] 2015-04-08 12:46
Same result no syntax highlighting and now indentation. I tried uninstalling the package and reinstalling it again; here is the package compilation log - I don't know if it is useful at all.

```
Leaving directory `/HOME/.emacs.d/elpa/enh-ruby-mode-20150312.1458'

Compiling file /HOME/.emacs.d/elpa/enh-ruby-mode-20150312.1458/enh-ruby-mode.el at Wed Apr  8 08:38:42 2015
Entering directory `/HOME/.emacs.d/elpa/enh-ruby-mode-20150312.1458/'
enh-ruby-mode.el:47:1:Warning: cl package required at runtime

In enh-ruby-mode:
enh-ruby-mode.el:265:39:Warning: assignment to free variable `erm-buff-num'
enh-ruby-mode.el:272:65:Warning: assignment to free variable `erm-e-w-status'
enh-ruby-mode.el:273:65:Warning: assignment to free variable
    `erm-full-parse-p'
enh-ruby-mode.el:251:30:Warning: assignment to free variable
    `need-syntax-check-p'
enh-ruby-mode.el:277:17:Warning: reference to free variable
    `ruby-smie-grammar'

In erm-ruby-get-process:
enh-ruby-mode.el:367:14:Warning: reference to free variable `erm-ruby-process'
enh-ruby-mode.el:368:25:Warning: reference to free variable `erm-parsing-p'
enh-ruby-mode.el:368:39:Warning: reference to free variable `erm-response'
enh-ruby-mode.el:380:34:Warning: assignment to free variable
    `erm-ruby-process'

In erm-reset-syntax-buffers:
enh-ruby-mode.el:414:43:Warning: assignment to free variable
    `need-syntax-check-p'

In erm-proc-string:
enh-ruby-mode.el:440:36:Warning: reference to free variable `erm-buff-num'

In erm-reset-buffer:
enh-ruby-mode.el:447:31:Warning: assignment to free variable `erm-buff-num'
enh-ruby-mode.el:447:31:Warning: reference to free variable `erm-buff-num'

In enh-ruby-local-enable-extra-keywords:
enh-ruby-mode.el:459:54:Warning: reference to free variable `erm-buff-num'

In enh-ruby-fontify-buffer:
enh-ruby-mode.el:524:11:Warning: assignment to free variable
    `erm-full-parse-p'

In erm-req-parse:
enh-ruby-mode.el:531:41:Warning: reference to free variable
    `need-syntax-check-p'
enh-ruby-mode.el:532:11:Warning: assignment to free variable
    `need-syntax-check-p'
enh-ruby-mode.el:545:23:Warning: reference to free variable `erm-full-parse-p'
enh-ruby-mode.el:565:13:Warning: assignment to free variable
    `erm-full-parse-p'
enh-ruby-mode.el:556:44:Warning: reference to free variable `erm-buff-num'

In erm-ready:
enh-ruby-mode.el:582:7:Warning: reference to free variable `erm-full-parse-p'
enh-ruby-mode.el:587:7:Warning: assignment to free variable
    `enh-ruby-font-names'

In enh-ruby-add-faces:
enh-ruby-mode.el:1051:15:Warning: assignment to free variable
    `erm-full-parse-p'
enh-ruby-mode.el:1069:38:Warning: reference to free variable
    `enh-ruby-font-names'

In erm-syntax-response:
enh-ruby-mode.el:1084:16:Warning: reference to free variable `erm-e-w-status'
enh-ruby-mode.el:1141:15:Warning: assignment to free variable `erm-e-w-status'

In erm-do-syntax-check:
enh-ruby-mode.el:1150:19:Warning: reference to free variable
    `need-syntax-check-p'
enh-ruby-mode.el:1151:21:Warning: assignment to free variable
    `need-syntax-check-p'

In erm-parse:
enh-ruby-mode.el:1175:17:Warning: assignment to free variable
    `erm-full-parse-p'
enh-ruby-mode.el:1190:13:Warning: reference to free variable
    `erm-full-parse-p'
enh-ruby-mode.el:1185:15:Warning: reference to free variable
    `need-syntax-check-p'

In end of data:
enh-ruby-mode.el:1198:1:Warning: the following functions are not known to be defined: smie-setup,
    ruby-smie-rules, ruby-smie--forward-token,
    ruby-smie--backward-token
```

**Comment by terryfinn** [comment] 2015-04-08 20:12
I didn't realize this was a fork of the main repo; I am going to submit this over on the main repo.

**Comment by zenspider** [comment] 2015-04-08 20:18
This is a fork because it is supported. The main repo is dead. Reopening.

**Comment by zenspider** [comment] 2015-04-08 20:19
Can you re-do the -Q line above, but bring up the `*Messages*` buffer and show any relevant output here?

**Comment by stoodfarback** [comment] 2015-04-08 20:44
That `init.el` works for me as well, starting with `emacs -Q`. The only way I could get it to not work is to remove my `ruby` executable from the `PATH`, but there is a clear message displayed in that case:

![screenshot-2015-04-08-13 42 49](https://cloud.githubusercontent.com/assets/45657/7054995/2d61c3e4-ddf5-11e4-89b3-56dc6fae133a.png)

Maybe your messages are being silenced somehow? Perhaps check the `*Messages*` buffer.

**Comment by terryfinn** [comment] 2015-04-09 00:42
Nothing interesting in the `*Messages*` buffer

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Loading package...done
Importing package-keyring.gpg...done
Contacting host: elpa.gnu.org:80
Contacting host: melpa.milkbox.net:80
<<< Type SPC or RET to bury the buffer list >>>
```

**Comment by zenspider** [comment] 2015-04-09 01:56
I'm afraid that without a repro there is nothing I can really do. I tested your repro on linux mint, debian, and xubuntu and they all worked fine once ruby was installed. You're going to have to investigate and figure out how to reproduce this on new system.

**Comment by zenspider** [comment] 2015-04-09 01:58
What ruby are you using? `ruby -v` to show.

What do you get from `ruby -rripper -e 'p Ripper::Version'`

**Comment by terryfinn** [comment] 2015-04-09 02:24
```bash
$ ruby -rripper -e 'p Ripper::Version'
"0.1.0"
```

**Comment by terryfinn** [comment] 2015-04-11 00:08
It seems that this issue might have to do with ruby 2.2.1. Everything works fine with ruby 2.2.0.

```elisp
(load "package")
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

;; Installs version 20150312.1458 of enh-ruby-package from melpa
(package-refresh-contents)
(package-install 'rbenv)
(package-install 'enh-ruby-mode)


(global-rbenv-mode)
(rbenv-use "2.2.0")
(add-to-list 'load-path "(path-to)/Enhanced-Ruby-Mode") ; must be added after any path containing old ruby-mode
(autoload 'enh-ruby-mode "enh-ruby-mode" "Major mode for ruby files" t)
(add-to-list 'auto-mode-alist '("\\.rb$" . enh-ruby-mode))
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))
```

**Comment by AnuragRamdasan** [comment] 2015-05-27 04:44
Has there been any update on this? My emacs still acts weird working with 2.2.1

**Comment by zenspider** [comment] 2015-06-05 01:23
Hardcoding my own setup to ruby 2.2.2 seems to work fine:

```
10007 % /Users/ryan/.rbenv/versions/2.2.2/bin/ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
10008 % /Users/ryan/.rbenv/versions/2.2.2/bin/ruby -rripper -e 'p Ripper::Version'
"0.1.0"
```

Please remove rbenv from the equation and try again. Otherwise, I still don't have a repro that I can work from.

**Comment by mijoharas** [comment] 2015-07-30 13:00
I have the same problem when using ruby `2.2.1` switching to `2.2.0` worked for me.

**Comment by jimmityglick** [comment] 2016-01-13 17:53
I had this problem using 2.2.2, setting enh-ruby-program to 2.2.0 worked for me.
$ ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
$ ruby -rripper -e 'p Ripper::Version'
"0.1.0"

i'm using rvm on linux.

**Comment by zenspider** [comment] 2016-08-18 00:26
Given that ruby 2.2.1 seems to be the isolated variable and 2.2.5 (as well as 2.3.1) is out... I'm going to assume this has a sufficient workaround ("don't use 2.2.1") and close this.

Please reopen if you think it isn't done yet.

**Closed by zenspider** 2016-08-18 00:26 UTC
