### ISSUE TITLE
Multi-line method chain (leading-dots) indentation

### ISSUE THREAD

**Issue by Eilie** [zenspider/enhanced-ruby-mode#83] opened 2015-05-29 22:12 UTC
This should have been fixed in https://github.com/zenspider/enhanced-ruby-mode/pull/47 but it doesn't work now:

``` ruby
foo
.bar
```

**Comment by zenspider** [comment] 2015-05-30 00:15
"it doesn't work" isn't descriptive. Please file a proper issue stating what you did, how to reproduce it, what you expected, and what actually happened.

**Comment by Eilie** [comment] 2015-05-30 10:41
@zenspider I did `foo` `RET` `.bar`, `.bar` should be indented, see https://github.com/zenspider/enhanced-ruby-mode/issues/46. Exact same issue.

**Comment by zenspider** [comment] 2015-06-04 21:26
I just added tests to show that it indents the way I expect. Please take a look at my last couple of commits to test and see if you agree. If not, a PR with a failing test would be appreciated (but not necessary).

**Comment by zenspider** [comment] 2015-06-08 22:02
anything?

**Comment by Eilie** [comment] 2015-06-14 10:36
@zenspider Tests looks correct, but in practice for some reason it doesn't indent leading dots(see first message example). Not sure why.

**Comment by zenspider** [comment] 2015-06-16 02:38
I've verified that the tests pass fine in batch mode and fail when all my stuff is loaded, so this is an external bug of some sort, but I haven't figured out how to isolate it yet.

**Comment by Kukunin** [comment] 2015-07-30 13:05
my two cents:

I've tried, I have the similar behaviour. When you type `one.two.three` `RET` `.four`, it have: 

```ruby
one.two.three
.four
```

But after `indent-region` command, it becomes valid:

```ruby
one.two.three
  .four
```

My suggestion, is that after `RET` you can't say for sure, do you want to start new command or continue the previous chain. 

So, indentation should be after first `.` symbol.

**Comment by bilus** [comment] 2016-03-24 22:27
`indent-region` doesn't work correctly for this:

```ruby
      def a
        x = b.eueu
        .eueu
        .eueu
      end
```

**Comment by iachettifederico** [comment] 2016-08-25 16:21
I have the same problem here. I'm using emacs 25 on a Linux Mint machine and rvm.

Is there anything I can do to help diagnose the problem?

**Comment by zw963** [comment] 2017-01-04 07:36
@zenspider , I have tried to only require enh-ruby-mode, no others.

It worked, But with my own config, it is not.

so, I think some others package is conflict with this.

I will try to find out it now.

Thanks

**Comment by zw963** [comment] 2017-01-04 08:11
Sorry for previous reply.

It not worked, even enh-ruby-mode is the only one package.
(previous reply opened by ruby-mode, not enh-ruby-mode)

Following is the step to reproduce:

1.  create `foo.rb` with: 
```rb
foo
.bar
```
2.  create ~/.emacs, with only following config:
```cl
;; Add enh-ruby-mode path to load-path.
(require 'enh-ruby-mode)
(let ((preferred-ruby-mode (if (fboundp 'enh-ruby-mode) 'enh-ruby-mode 'ruby-mode)))
  (add-to-list 'auto-mode-alist
               `("\\.\\(rb\\|rake\\|ru\\|gemspec\\|jbuilder\\|rjs\\)$"
                 . ,preferred-ruby-mode))
  (add-to-list 'auto-mode-alist
               `("Rakefile\\|Gemfile\\|Capfile\\|Guardfile$"
                 . ,preferred-ruby-mode))
  (add-to-list 'interpreter-mode-alist `("ruby" . ,preferred-ruby-mode))
  )
```

3.  emacs foo.rb

4. M-x eval-expression with `(indent-region (point-min) (point-max))`

5. file keep not changed.

emacs version:  24.5.1, Thanks.

**Comment by zenspider** [comment] 2017-01-08 02:41
So I've confirmed that I have a new test failure on emacs 25 that I didn't have under 24.x. Not sure how to fix it yet...

**Comment by zw963** [comment] 2017-01-09 07:51
@zenspider , I have update to emacs 25.1 now, It can be reproduce too.

Hope could be fix soon. thanks.

I guess this bug is relative to this? #102 ?

**Comment by zw963** [comment] 2017-01-11 06:29
@zenspider , Is there a workaround to skip only multi-line method chain indentation ??

When I run `(indent-region (point-min) (point-max))`, always get wrong position.

Thanks.

**Comment by zw963** [comment] 2017-02-03 08:16
Hi, all !

I found the key reason to reproduce this issue.

just switch to old ruby 2.1.6, indent worked now!

**Comment by zw963** [comment] 2017-04-19 06:57
@zenspider , happy to see you keep reply issue for this project.

do you see my previous comment?

This issue not happen on Ruby 2.1, but happen on 2.2.

**Comment by zw963** [comment] 2017-06-14 10:32
hi, @zenspider , I run enh-ruby-mode included ``lexer.rb`` with following command seperately
```sh
ruby-2.1.3 lexer.rb 1.rb >  ruby-2.1.3.txt
```

```sh
ruby-2.2.4 lexer.rb 1.rb > ruby-2.2.4.txt
```

```sh
ruby-2.3.3 lexor.rb 1.rb > ruby-2.3.3.txt
```

following is 1.rb content:

```1.rb
method
  .call(1)
  .call(2)
  .call(3)
```

The 2.1.3 result is:
```sh
[[[1, 0], :on_ident, "method"],
 [[1, 6], :on_period, "\n"],
 [[2, 0], :on_ident, "  .call"],
 [[2, 7], :on_lparen, "("],
 [[2, 8], :on_int, "1"],
 [[2, 9], :on_rparen, ")"],
 [[2, 10], :on_period, "\n"],
 [[3, 0], :on_ident, "  .call"],
 [[3, 7], :on_lparen, "("],
 [[3, 8], :on_int, "2"],
 [[3, 9], :on_rparen, ")"],
 [[3, 10], :on_period, "\n"],
 [[4, 0], :on_ident, "  .call"],
 [[4, 7], :on_lparen, "("],
 [[4, 8], :on_int, "3"],
 [[4, 9], :on_rparen, ")"],
 [[4, 10], :on_nl, "\n"]]

[:program,
 [:stmts_add,
  [:stmts_new],
  [:method_add_arg,
   [:call,
    [:method_add_arg,
     [:call,
      [:method_add_arg,
       [:call,
        [:vcall, [:@ident, "method", [1, 0]]],
        :".",
        [:@ident, "  .call", [2, 0]]],
       [:arg_paren,
        [:args_add_block,
         [:args_add, [:args_new], [:@int, "1", [2, 8]]],
         false]]],
      :".",
      [:@ident, "  .call", [3, 0]]],
     [:arg_paren,
      [:args_add_block,
       [:args_add, [:args_new], [:@int, "2", [3, 8]]],
       false]]],
    :".",
    [:@ident, "  .call", [4, 0]]],
   [:arg_paren,
    [:args_add_block,
     [:args_add, [:args_new], [:@int, "3", [4, 8]]],
     false]]]]]

[:program,
 [[:method_add_arg,
   [:call,
    [:method_add_arg,
     [:call,
      [:method_add_arg,
       [:call,
        [:vcall, [:@ident, "method", [1, 0]]],
        :".",
        [:@ident, "  .call", [2, 0]]],
       [:arg_paren, [:args_add_block, [[:@int, "1", [2, 8]]], false]]],
      :".",
      [:@ident, "  .call", [3, 0]]],
     [:arg_paren, [:args_add_block, [[:@int, "2", [3, 8]]], false]]],
    :".",
    [:@ident, "  .call", [4, 0]]],
   [:arg_paren, [:args_add_block, [[:@int, "3", [4, 8]]], false]]]]]
```

And, ruby-2.2.4 same as ruby-2.3.3, content is:
```sh
[[[1, 0], :on_ident, "method"],
 [[1, 6], :on_ignored_nl, "\n"],
 [[2, 0], :on_sp, "  "],
 [[2, 2], :on_period, "."],
 [[2, 3], :on_ident, "call"],
 [[2, 7], :on_lparen, "("],
 [[2, 8], :on_int, "1"],
 [[2, 9], :on_rparen, ")"],
 [[2, 10], :on_ignored_nl, "\n"],
 [[3, 0], :on_sp, "  "],
 [[3, 2], :on_period, "."],
 [[3, 3], :on_ident, "call"],
 [[3, 7], :on_lparen, "("],
 [[3, 8], :on_int, "2"],
 [[3, 9], :on_rparen, ")"],
 [[3, 10], :on_ignored_nl, "\n"],
 [[4, 0], :on_sp, "  "],
 [[4, 2], :on_period, "."],
 [[4, 3], :on_ident, "call"],
 [[4, 7], :on_lparen, "("],
 [[4, 8], :on_int, "3"],
 [[4, 9], :on_rparen, ")"],
 [[4, 10], :on_nl, "\n"]]

[:program,
 [:stmts_add,
  [:stmts_new],
  [:method_add_arg,
   [:call,
    [:method_add_arg,
     [:call,
      [:method_add_arg,
       [:call,
        [:vcall, [:@ident, "method", [1, 0]]],
        :".",
        [:@ident, "call", [2, 3]]],
       [:arg_paren,
        [:args_add_block,
         [:args_add, [:args_new], [:@int, "1", [2, 8]]],
         false]]],
      :".",
      [:@ident, "call", [3, 3]]],
     [:arg_paren,
      [:args_add_block,
       [:args_add, [:args_new], [:@int, "2", [3, 8]]],
       false]]],
    :".",
    [:@ident, "call", [4, 3]]],
   [:arg_paren,
    [:args_add_block,
     [:args_add, [:args_new], [:@int, "3", [4, 8]]],
     false]]]]]

[:program,
 [[:method_add_arg,
   [:call,
    [:method_add_arg,
     [:call,
      [:method_add_arg,
       [:call,
        [:vcall, [:@ident, "method", [1, 0]]],
        :".",
        [:@ident, "call", [2, 3]]],
       [:arg_paren, [:args_add_block, [[:@int, "1", [2, 8]]], false]]],
      :".",
      [:@ident, "call", [3, 3]]],
     [:arg_paren, [:args_add_block, [[:@int, "2", [3, 8]]], false]]],
    :".",
    [:@ident, "call", [4, 3]]],
   [:arg_paren, [:args_add_block, [[:@int, "3", [4, 8]]], false]]]]]
```

Since ruby 2.2.0, ripper is updated, I think this is the reason cause ident
incorrect.

Thanks

**Comment by zw963** [comment] 2017-07-17 13:55
It seem like @zenspider guys disappear from earth for a long time.

When to return to earth, hope I can know. : )

**Comment by darrenboyd** [comment] 2017-07-21 16:29
I wonder if: `[1, 6], :on_period, "\n"]`

changing to: `[2, 2], :on_period, "."]`

Is related to this code?

https://github.com/zenspider/enhanced-ruby-mode/blob/master/ruby/erm_buffer.rb#L451-L455

**Comment by zw963** [comment] 2017-07-22 09:33
@darrenboyd , Do you try to fix it? I will use your's fork.

**Comment by darrenboyd** [comment] 2017-07-24 14:49
Sorry, @zw963, I have no fix. I tried to figure out how any of this worked, but was unable to wrap my head around it :confused:

**Comment by zenspider** [comment] 2017-08-15 11:04
I'm back... not sure I can fix this one... but I'm back :)

**Comment by zw963** [comment] 2017-08-15 13:48
@zenspider , welcome to earth! 😃

**Comment by sadhu89** [comment] 2017-08-19 07:41
Welcome back @zenspider!
Does anybody know any workaround for this issue? Thanks!

**Comment by zenspider** [comment] 2017-08-22 23:48
This should be fixed.

**Closed by zenspider** 2017-08-22 23:48 UTC

**Comment by zw963** [comment] 2017-08-23 09:10
It worked, fallback to use enh-ruby-mode again, Thanks!
